version: "3.6"
services:
  ftf_user:
    container_name: ftf_user
    build:
      context: ./microservices/ftf-user
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    ports:
      - 3001:3001
    networks:
      - ftf-network
      - usernet
    depends_on:
      - mysql_user

networks:
  ftf-network:
    driver: bridge
  usernet:
    external:
      name: usernet