version: "3.6"
services:
  mysql_simple2:
    container_name: mysql_simple2
    image: mysql:latest
    command: >
      mysqld
        --default-authentication-plugin=mysql_native_password
        --skip-mysqlx
        --transaction-isolation=READ-COMMITTED
        --innodb_rollback_on_timeout
        --innodb_lock_wait_timeout=10
        --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: nestjs
    ports:
      - 33070:3306
    networks:
    - ftf-network

  mysql_user:
    container_name: mysql_user
    image: mysql:latest
    command: >
      mysqld
        --default-authentication-plugin=mysql_native_password
        --skip-mysqlx
        --transaction-isolation=READ-COMMITTED
        --innodb_rollback_on_timeout
        --innodb_lock_wait_timeout=10
        --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: user_db
    ports:
      - 33080:3306
    networks:
      - ftf-network
      - sharednet

networks:
  ftf-network:
    driver: bridge
  sharednet:
    external:
      name: sharednet