version: "3.6"
services:
  ftf_auth:
    container_name: ftf_auth
    build:
      context: ./microservices/ftf-auth
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    ports:
      - 4001:3001
    networks:
      - ftf-network
      - sharednet
    depends_on:
      - mysql_user

networks:
  ftf-network:
    driver: bridge
  sharednet:
    external:
      name: sharednet