name: ftf-backend-CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'ftf-backend-v1' }}

jobs:
      
  docker:
    name: Run docker-containers
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Create docker network for user service
      run: docker network create usernet || true
    - name: Run docker-compose files
      run: docker-compose -f docker-compose-db.yml -f docker-compose-services.yml
    - name: Check running containers
      run: docker ps -a
    - name: Install packages
      run: yarn install
    - name: Prebuild project
      run: yarn run prebuild
    - name: Build project
      run: yarn run build