name: ftf-backend-CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
#set environment variables 

jobs:
      
  docker:
    name: Run docker-containers
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install packages
      run: yarn install
    - name: Prebuild project
      run: yarn run prebuild
    - name: Build project
      run: yarn run build